// src/pages/search-as-you-type/search-as-you-type.component.ts
import { Component, computed, DestroyRef, signal, WritableSignal } from '@angular/core';
import { SuggestedWord } from './suggested-word';
import { catchError, debounceTime, distinctUntilChanged, filter, map, of, Subject, switchMap, tap } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { FormsModule } from "@angular/forms";
import { FaIconComponent } from "@fortawesome/angular-fontawesome";
import { faCircleInfo, faHourglass, faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";

type State = 'loading' | 'empty' | 'initial' | 'loaded';

@Component({
  selector: 'app-search-as-you-type',
  imports: [
    FormsModule,
    FaIconComponent
  ],
  templateUrl: './search-as-you-type.component.html',
  styleUrl: './search-as-you-type.component.scss',
})
export class SearchAsYouType {
  ICONS = {
    alert: faTriangleExclamation,
    hourglass: faHourglass,
    info: faCircleInfo,
  }
  MIN_SEARCH_LENGTH = 3;

  searchString = signal('');
  private showLoading = signal(false);
  state = computed<State>(() => {
    if (this.showLoading()) {
      return 'loading';
    }
    if (this.searchString().length < this.MIN_SEARCH_LENGTH) {
      return 'initial';
    }
    if (this.suggestions().length === 0) {
      return 'empty'
    }
    return 'loaded';
  })

  suggestions: WritableSignal<SuggestedWord[]> = signal([]);

  private cache = new Map<string, SuggestedWord[]>();
  private searchSubject = new Subject<string>();

  constructor(private http: HttpClient, destroyRef: DestroyRef) {
    this.searchSubject.asObservable().pipe(
      debounceTime(300),
      distinctUntilChanged(),
      filter((searchString: string) => searchString.length >= this.MIN_SEARCH_LENGTH),
      tap(() => this.showLoading.set(true)),
      switchMap((searchString) => {
        const cachedSuggestion = this.cache.get(searchString);
        if (cachedSuggestion) {
          return of(cachedSuggestion);
        } else {
          return this.http.get<SuggestedWord[]>(`https://api.datamuse.com/sug?s=${searchString}`)
            .pipe(
              tap((suggestions) => {
                this.cache.set(searchString, suggestions)
              }),
              catchError(() => of([])))
        }
      }),
      map((suggestionDTOs) => suggestionDTOs.sort((s) => s.score)),
      takeUntilDestroyed(destroyRef),
    ).subscribe({
      next: (suggestions: SuggestedWord[]) => {
        this.suggestions.set(suggestions);
        this.showLoading.set(false);
      },
      error: () => { this.showLoading.set(false); }
    });
  }

  onInputChange(searchString: string) {
    this.searchSubject.next(searchString);
  }
}

<div class="description">
  <fa-icon
    [icon]="ICONS.info"
    [size]="'2x'">
  </fa-icon>
  <div class="description__text">
    <p>
      An example of a reactive search component demonstrating advanced RxJS patterns.
    </p>
    Features include:
    <ul>
      <li>intelligent API request cancellation</li>
      <li>a custom caching layer for instant data retrieval</li>
      <li>use of Angular Signals for optimized change detection</li>
    </ul>

    The code can be found
    <a href="https://github.com/serenasychan/serenasychan.github.io/tree/source/src/pages/search-as-you-type"
       target="_blank" rel="noopener noreferrer">here</a>
  </div>
</div>

<div class="content">
  <label>
    Search for words starting with:
  </label>
  <input
    id="searchString"
    type="text"
    [(ngModel)]="searchString"
    (ngModelChange)="onInputChange($event)"
  >

  @switch (state()) {
    @case ('loading') {
      <div class="noResults">
        <fa-icon [icon]="ICONS.hourglass"></fa-icon>
        Loading ...
      </div>
    }
    @case ('initial') {
      <div class="noResults">
        <fa-icon [icon]="ICONS.alert"></fa-icon>
        Please enter at least {{ MIN_SEARCH_LENGTH }} characters
      </div>
    }
    @case ('empty') {
      <div class="noResults">
        No matches found.
      </div>
    }
    @case ('loaded') {
      <div class="results">
        <ol>
          @for (suggestion of suggestions(); track suggestion.word) {
            <li>
              {{ suggestion.word }}
            </li>
          }
        </ol>
      </div>
    }
  }
</div>

// src/pages/search-as-you-type/search-as-you-type-react.tsx
import React from 'react';
import { SuggestedWord } from './suggested-word';
import { faCircleInfo, faHourglass, faSearch, faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { IconDefinition } from "@fortawesome/free-brands-svg-icons";

const MIN_SEARCH_LENGTH = 3;
const cache = new Map();
type SearchState = 'loading' | 'initial' | 'empty' | 'loaded';
const MESSAGES: Record<SearchState, string> = {
  loading: "Loading...",
  initial: `Please enter at least ${MIN_SEARCH_LENGTH} characters`,
  empty: "No matches found.",
  loaded: "" // Unused but satisfies indexer
};

const ICONS: Record<string, IconDefinition> = {
  initial: faTriangleExclamation,
  loading: faHourglass,
  info: faCircleInfo,
  empty: faSearch,
}

export const SearchAsYouTypeReactComponent = () => {
  // Derived state from Angular signals to React useState
  const [searchString, setSearchString] = React.useState('');
  const [suggestions, setSuggestions] = React.useState<string[] | null>(null);
  const [isLoading, setIsLoading] = React.useState(false);

  // Replaced Angular computed with React useMemo
  const currentState: SearchState = React.useMemo(() => {
    if (searchString.length < MIN_SEARCH_LENGTH) return 'initial';
    if (isLoading) return 'loading';
    if (suggestions === null) return 'empty';
    return 'loaded';
  }, [isLoading, searchString, suggestions]);

  React.useEffect(() => {
    const controller = new AbortController();
    const signal = controller.signal;

    // 1. Filter out inputs less than minimum length
    if (searchString.length < MIN_SEARCH_LENGTH) {
      setSuggestions([]);
      return;
    }

    let active = true;

    // 2. Debounce: wait 300ms
    const timer = setTimeout(async() => {
      // 3. Cache check
      if (cache.has(searchString) && active) {
        setSuggestions(cache.get(searchString));
        return;
      }

      setSuggestions(null);
      setIsLoading(true);

      try {
        const response = await fetch(`https://api.datamuse.com/sug?s=${searchString}`, { signal });
        if (!response.ok) throw new Error('Network error');

        const data: SuggestedWord[] = await response.json();

        // 4. Sort results
        const sortedData = data.length === 0
          ? null
          : data.sort((a, b) => a.score - b.score)
            .map((s) => s.word);

        if (active) {
          cache.set(searchString, sortedData);
          setSuggestions(sortedData);
          setIsLoading(false);
        }
      } catch (error) {
        if (active) {
          setSuggestions(null);
        }
      } finally {
        if (active) setIsLoading(false);
      }
    }, 300);

    // 5. Cleanup
    return () => {
      active = false;         // "Unsubscribe" UI
      controller.abort();     // "Unsubscribe" Network
      clearTimeout(timer);    // "Unsubscribe" Timer
    };
  }, [searchString]);

  return (
    <div className='search-container'>
      <input
        type="text"
        value={searchString}
        onChange={(e) => setSearchString(e.target.value)}
        placeholder="Search for words starting with..."
      />

      {currentState === 'loaded' && (
        <div className='results'>
          <ol>
            {suggestions?.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ol>
        </div>
      ) || (
        <div className='noResults' aria-live="polite" role="status">
          <div className='fa-icon'>
            <FontAwesomeIcon icon={ICONS[currentState]} />
          </div>
          {MESSAGES[currentState]}
        </div>
      )}
    </div>
  );
}
